### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by jcmunav63** [Xghayor/Music-Festival#6]
Good work so far, Ghayoor.
Your webpage is looking so great.
Excellent design!
I have some comments in order to improve some parts of your webpage...
1) You can add a button to show less (hide) the speakers that you show when you click the MORE button.
2) You can add also the other options on the mobile menu (you only show the about and home options).
Have a great time and congratulations.

**Comment by Movgto** [comment]
You have made a great job with the project, I think there's nothing else to do congratulations 😄

**Comment by Xghayor** [comment]
Thanks Juan for pointing out few changes, i will implement that later on when it is required by the Managment.
Thank you Gumaro.
